--CREATE DATABASE COMPANY;

--CREATE DATABASE ECOMMERCE;

-- USE NomeDoDataBase
-- GO serve oara executar o restante

USE COMPANY
GO

DROP TABLE IF EXISTS dbo.EMPLOYEE;

DROP TABLE IF EXISTS dbo.WORKS_ON;
DROP TABLE IF EXISTS dbo.DEPENDENT;
DROP TABLE IF EXISTS dbo.DEPT_LOCATIONS;
DROP TABLE IF EXISTS dbo.PROJECT;
DROP TABLE IF EXISTS dbo.EMPLOYEE;
DROP TABLE IF EXISTS dbo.DEPARTMENT;
GO

CREATE TABLE dbo.EMPLOYEE (
    Fname VARCHAR(50) NOT NULL,
    Minit CHAR(1),
    Lname VARCHAR(50) NOT NULL,
    Ssn CHAR(9) NOT NULL,
    Bdate DATE,
    Address VARCHAR(150),
    Sex CHAR(1),
    Salary DECIMAL(10,2),
    Super_ssn CHAR(9),
    Dno INT,
    
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (Ssn)
);

CREATE TABLE dbo.DEPARTMENT (
    Dname VARCHAR(50) NOT NULL,
    Dnumber INT NOT NULL,
    Mgr_ssn CHAR(9),
    Mgr_start_date DATE,

    CONSTRAINT PK_DEPARTMENT PRIMARY KEY (Dnumber)
);

/*
    Cria o relacionamento entre as FKs
*/
ALTER TABLE dbo.EMPLOYEE
ADD CONSTRAINT FK_EMPLOYEE_DEPARTMENT
FOREIGN KEY (Dno)
REFERENCES dbo.DEPARTMENT(Dnumber);

ALTER TABLE dbo.EMPLOYEE
ADD CONSTRAINT FK_EMPLOYEE_SUPERVISOR
FOREIGN KEY (Super_ssn)
REFERENCES dbo.EMPLOYEE(Ssn);

ALTER TABLE dbo.DEPARTMENT
ADD CONSTRAINT FK_DEPARTMENT_MANAGER
FOREIGN KEY (Mgr_ssn)
REFERENCES dbo.EMPLOYEE(Ssn);

CREATE TABLE dbo.PROJECT (
    Pname VARCHAR(100) NOT NULL,
    Pnumber INT NOT NULL,
    Plocation VARCHAR(100),
    Dnum INT,

    CONSTRAINT PK_PROJECT PRIMARY KEY (Pnumber),

    CONSTRAINT FK_PROJECT_DEPARTMENT
    FOREIGN KEY (Dnum)
    REFERENCES dbo.DEPARTMENT(Dnumber)
);

CREATE TABLE dbo.DEPT_LOCATIONS (
    Dnumber INT NOT NULL,
    Dlocation VARCHAR(100) NOT NULL,

    CONSTRAINT PK_DEPT_LOCATIONS
    PRIMARY KEY (Dnumber, Dlocation),

    CONSTRAINT FK_DEPT_LOCATIONS_DEPARTMENT
    FOREIGN KEY (Dnumber)
    REFERENCES dbo.DEPARTMENT(Dnumber)
);

CREATE TABLE dbo.WORKS_ON (
    Essn CHAR(9) NOT NULL,
    Pno INT NOT NULL,
    Hours DECIMAL(5,2),

    CONSTRAINT PK_WORKS_ON
    PRIMARY KEY (Essn, Pno),

    CONSTRAINT FK_WORKS_ON_EMPLOYEE
    FOREIGN KEY (Essn)
    REFERENCES dbo.EMPLOYEE(Ssn),

    CONSTRAINT FK_WORKS_ON_PROJECT
    FOREIGN KEY (Pno)
    REFERENCES dbo.PROJECT(Pnumber)
);

CREATE TABLE dbo.DEPENDENT (
    Essn CHAR(9) NOT NULL,
    Dependent_name VARCHAR(50) NOT NULL,
    Sex CHAR(1),
    Bdate DATE,
    Relationship VARCHAR(50),

    CONSTRAINT PK_DEPENDENT
    PRIMARY KEY (Essn, Dependent_name),

    CONSTRAINT FK_DEPENDENT_EMPLOYEE
    FOREIGN KEY (Essn)
    REFERENCES dbo.EMPLOYEE(Ssn)
);