SELECT *
FROM COMPANY.DBO.EMPLOYEE
WHERE Salary >= 4000 AND Salary <=5000;

SET STATISTICS IO ON;
SET STATISTICS TIME ON;

SELECT 
    E.Fname,
    E.Lname,
    D.Dname
FROM COMPANY.dbo.EMPLOYEE E
JOIN COMPANY.dbo.DEPARTMENT D ON E.Dno = D.Dnumber;

SELECT *
FROM COMPANY.dbo.EMPLOYEE
WHERE Dno = 2;